org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2048m"
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Increase network timeouts for slow connections
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
