package com.paperflow.app.data.local.file

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.InputStream
import java.io.OutputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM encryption using Android Keystore (SR-ENC-001, SR-ENC-004).
 * Keys never hardcoded (SR-ENC-005). Never stored externally.
 * GCM mode: authenticated encryption, no padding oracle vulnerability.
 */
@Singleton
class EncryptionManager @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    companion object {
        private const val KEY_ALIAS = "paperflow_vault_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val ALGORITHM = KeyProperties.KEY_ALGORITHM_AES
        private const val BLOCK_MODE = KeyProperties.BLOCK_MODE_GCM
        private const val PADDING = KeyProperties.ENCRYPTION_PADDING_NONE
        private const val TRANSFORMATION = "$ALGORITHM/$BLOCK_MODE/$PADDING"
        private const val GCM_TAG_LENGTH = 128
        private const val IV_LENGTH = 12
    }

    // ── Key Management ────────────────────────────────────────────────────────

    /** Get or create AES-256 key in Android Keystore. */
    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        ks.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }

        val keyGen = KeyGenerator.getInstance(ALGORITHM, ANDROID_KEYSTORE)
        keyGen.init(
            KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setKeySize(256)
                .setBlockModes(BLOCK_MODE)
                .setEncryptionPaddings(PADDING)
                .setUserAuthenticationRequired(false) // Key accessible without auth (vault auth is at app level)
                .build()
        )
        return keyGen.generateKey()
    }

    // ── Encrypt / Decrypt Streams ─────────────────────────────────────────────

    /**
     * Encrypts [input] to [output].
     * Format: [IV (12 bytes)] + [ciphertext with GCM tag]
     */
    fun encryptStream(input: InputStream, output: OutputStream) {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv // 12-byte GCM IV, generated by cipher
        output.write(iv) // Prepend IV
        CipherOutputStream(output, cipher).use { cos ->
            input.copyTo(cos)
        }
    }

    /**
     * Decrypts [input] to [output].
     * Reads IV from first 12 bytes, then decrypts rest.
     */
    fun decryptStream(input: InputStream, output: OutputStream) {
        val key = getOrCreateKey()
        val iv = ByteArray(IV_LENGTH)
        val read = input.read(iv)
        require(read == IV_LENGTH) { "Invalid encrypted file: missing IV" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH, iv))
        CipherInputStream(input, cipher).use { cis ->
            cis.copyTo(output)
        }
    }

    /** Encrypt a file, return the encrypted output file. */
    fun encryptFile(source: File, dest: File): File {
        source.inputStream().use { input ->
            dest.outputStream().use { output ->
                encryptStream(input, output)
            }
        }
        return dest
    }

    /** Decrypt a file, return the decrypted output file. */
    fun decryptFile(source: File, dest: File): File {
        source.inputStream().use { input ->
            dest.outputStream().use { output ->
                decryptStream(input, output)
            }
        }
        return dest
    }

    /**
     * Decrypt to a temp file. Caller MUST delete after use (SR-ENC-003).
     * Use the returned [AutoCloseable] to ensure cleanup even on exception.
     */
    fun decryptToTemp(source: File, tempFile: File): TemporaryDecryptedFile {
        decryptFile(source, tempFile)
        return TemporaryDecryptedFile(tempFile)
    }

    /** Checks whether the keystore key is available. */
    fun isKeyAvailable(): Boolean = try {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        ks.containsAlias(KEY_ALIAS)
    } catch (e: Exception) { false }
}

/**
 * Wraps a temporarily decrypted file. Close to securely delete (SR-ENC-003).
 */
class TemporaryDecryptedFile(val file: File) : AutoCloseable {
    override fun close() {
        if (file.exists()) {
            // Zero-fill before delete
            try {
                file.outputStream().use { it.write(ByteArray(file.length().toInt())) }
            } finally {
                file.delete()
            }
        }
    }
}
